export const EEG_MODULE_START_RECORDING = "EEG_MODULE_START_RECORDING";
export const EEG_MODULE_START_ANALYSIS = "EEG_MODULE_START_ANALYSIS";

export const EEG_MODULE_SET_RESULT = "EEG_MODULE_SET_RESULT";

export const EEG_MODULE_RESET = "EEG_MODULE_RESET";

export const EEG_MODULE_SET_KOCH_RESPONSE = "EEG_MODULE_SET_KOCH_RESPONSE";
export const EEG_MODULE_SET_RUDY_RESPONSE = "EEG_MODULE_SET_RUDY_RESPONSE";
export const EEG_MODULE_SET_ALVARO_RESPONSE = "EEG_MODULE_SET_ALVARO_RESPONSE";
