export const EEG_MODULE_START_RECORDING = "EEG_MODULE_START_RECORDING";
export const EEG_MODULE_START_ANALYSIS = "EEG_MODULE_START_ANALYSIS";

export const EEG_MODULE_SET_RESULT = "EEG_MODULE_SET_RESULT";

export const EEG_MODULE_RESET = "EEG_MODULE_RESET";
