export const MICRO_MODULE_START_RECORDING = "MICRO_MODULE_START_RECORDING";
export const MICRO_MODULE_START_ANALYSIS = "MICRO_MODULE_START_ANALYSIS";

export const MICRO_MODULE_SET_RESULT = "MICRO_MODULE_SET_RESULT";

export const MICRO_MODULE_RESET = "MICRO_MODULE_RESET";

export const MICRO_MODULE_SET_CASTRO_RESPONSE =
  "MICRO_MODULE_SET_CASTRO_RESPONSE";
export const MICRO_MODULE_SET_NORIEGA_RESPONSE =
  "MICRO_MODULE_SET_NORIEGA_RESPONSE";
