export const MICRO_MODULE_START_RECORDING = "MICRO_MODULE_START_RECORDING";
export const MICRO_MODULE_START_ANALYSIS = "MICRO_MODULE_START_ANALYSIS";

export const MICRO_MODULE_SET_RESULT = "MICRO_MODULE_SET_RESULT";

export const MICRO_MODULE_RESET = "MICRO_MODULE_RESET";
