export const TEST_START_QUESTION = "TEST_START_QUESTION";
export const TEST_START_ANSWER = "TEST_START_ANSWER";
export const TEST_FINISH_ANSWER = "TEST_FINISH_ANSWER";
export const TEST_RESET = "TEST_RESET";
export const TEST_CONNECT_SOCKET = "TEST_CONNECT_SOCKET";

export const TEST_SET_CHAN_RESPONSE = "TEST_SET_CHAN_RESPONSE";
export const TEST_SET_KOCH_RESPONSE = "TEST_SET_KOCH_RESPONSE";
