export const TEST_START_QUESTION = "TEST_START_QUESTION";
export const TEST_START_ANSWER = "TEST_START_ANSWER";
export const TEST_FINISH_ANSWER = "TEST_FINISH_ANSWER";
export const TEST_RESET = "TEST_RESET";
