export const VOICE_MODULE_START_RECORDING = "VOICE_MODULE_START_RECORDING";
export const VOICE_MODULE_START_ANALYSIS = "VOICE_MODULE_START_ANALYSIS";

export const VOICE_MODULE_SET_RESULT = "VOICE_MODULE_SET_RESULT";

export const VOICE_MODULE_RESET = "VOICE_MODULE_RESET";
