export const VOICE_MODULE_START_RECORDING = "VOICE_MODULE_START_RECORDING";
export const VOICE_MODULE_START_ANALYSIS = "VOICE_MODULE_START_ANALYSIS";

export const VOICE_MODULE_SET_RESULT = "VOICE_MODULE_SET_RESULT";

export const VOICE_MODULE_RESET = "VOICE_MODULE_RESET";

export const VOICE_MODULE_SET_OLGA_RESPONSE = "VOICE_MODULE_SET_OLGA_RESPONSE";
export const VOICE_MODULE_SET_LEONEL_RESPONSE =
  "VOICE_MODULE_SET_LEONEL_RESPONSE";
export const VOICE_MODULE_SET_CHAN_RESPONSE = "VOICE_MODULE_SET_CHAN_RESPONSE";
